-- AlterTable
ALTER TABLE "Prospect" ADD COLUMN "landingpageTemplateId" TEXT,
ADD COLUMN "firstName" TEXT,
ADD COLUMN "lastName" TEXT,
ADD COLUMN "videoUrl" TEXT,
ADD COLUMN "calendarUrl" TEXT,
ADD COLUMN "customPainPoint" TEXT,
ADD COLUMN "customHeroHeadline" TEXT,
ADD COLUMN "customHeroSubline" TEXT,
ADD COLUMN "customHeroBodyText" TEXT,
ADD COLUMN "customHeroCtaText" TEXT,
ADD COLUMN "customHeroCtaUrl" TEXT,
ADD COLUMN "personalVideoUrl" TEXT,
ADD COLUMN "personalVideoThumbnailUrl" TEXT,
ADD COLUMN "explainerVideoUrl" TEXT,
ADD COLUMN "individualCtaText" TEXT;

-- CreateTable
CREATE TABLE "LandingpageTemplate" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "logoUrl" TEXT,
    "primaryColor" TEXT NOT NULL DEFAULT '#101828',
    "accentColor" TEXT NOT NULL DEFAULT '#14b8a6',
    "backgroundMode" TEXT NOT NULL DEFAULT 'light',
    "defaultCtaText" TEXT NOT NULL DEFAULT 'Gratis Termin vereinbaren',
    "defaultCtaUrl" TEXT,
    "heroEnabled" BOOLEAN NOT NULL DEFAULT true,
    "heroEyebrow" TEXT,
    "heroHeadline" TEXT NOT NULL,
    "heroSubheadline" TEXT,
    "heroBodyText" TEXT,
    "heroCtaText" TEXT,
    "heroCtaUrl" TEXT,
    "heroSecondaryCtaText" TEXT,
    "heroSecondaryCtaUrl" TEXT,
    "heroVideoPosition" TEXT NOT NULL DEFAULT 'right',
    "heroLayout" TEXT NOT NULL DEFAULT 'video_right',
    "personalVideoEnabled" BOOLEAN NOT NULL DEFAULT true,
    "personalVideoUrl" TEXT,
    "personalVideoThumbnailUrl" TEXT,
    "personalVideoTitle" TEXT,
    "personalVideoButtonText" TEXT NOT NULL DEFAULT 'Persönliches Video ansehen',
    "explainerVideoEnabled" BOOLEAN NOT NULL DEFAULT true,
    "explainerVideoUrl" TEXT,
    "explainerVideoThumbnailUrl" TEXT,
    "explainerVideoTitle" TEXT,
    "explainerVideoSubline" TEXT,
    "explainerVideoButtonText" TEXT NOT NULL DEFAULT 'Erklärvideo ansehen',
    "explainerCtaText" TEXT,
    "explainerCtaUrl" TEXT,
    "comparisonEnabled" BOOLEAN NOT NULL DEFAULT true,
    "comparisonHeadline" TEXT,
    "beforeItems" TEXT[],
    "afterItems" TEXT[],
    "approachEnabled" BOOLEAN NOT NULL DEFAULT true,
    "approachHeadline" TEXT,
    "approachText" TEXT,
    "faqEnabled" BOOLEAN NOT NULL DEFAULT true,
    "faqJson" JSONB NOT NULL,
    "finalCtaEnabled" BOOLEAN NOT NULL DEFAULT true,
    "finalCtaHeadline" TEXT,
    "finalCtaText" TEXT,
    "finalCtaUrl" TEXT,
    "footerText" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LandingpageTemplate_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Prospect" ADD CONSTRAINT "Prospect_landingpageTemplateId_fkey" FOREIGN KEY ("landingpageTemplateId") REFERENCES "LandingpageTemplate"("id") ON DELETE SET NULL ON UPDATE CASCADE;
