ALTER TABLE "VideoAsset"
ADD COLUMN "filename" TEXT NOT NULL DEFAULT '',
ADD COLUMN "originalName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "mimeType" TEXT NOT NULL DEFAULT 'video/mp4',
ADD COLUMN "sizeBytes" INTEGER NOT NULL DEFAULT 0;
