ALTER TABLE "Prospect" ADD COLUMN "icpScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "fitScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "icpCategory" TEXT NOT NULL DEFAULT 'low',
ADD COLUMN "painSignals" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "isHotLead" BOOLEAN NOT NULL DEFAULT false;
